name: "Build Request"
description: "Request a new build by selecting components."
title: "[Build] New Build Request"
labels: [build-request]
body:
  - type: markdown
    attributes:
      value: "### Select components to build:"
  - type: checkboxes
    id: build_components
    attributes:
      label: "Components:"
      options:
        - label: "File Validation"
        - label: "Essential Validation"
        - label: "Metadata Validation"
        - label: "Export Validation"
        - label: "PvPuller"
