Config:
    # service type value in metadata, file and metadata
    service-type: metadata
    models-loc: https://raw.githubusercontent.com/CBIIT/crdc-datahub-models/
    cde-data-element-api: https://cadsrapi.cancer.gov/rad/NCIAPI/1.0/api/DataElement/
   