#define constants, enums, etc.
#config 
MONGO_DB = "connection-str"
SQS_NAME = "sqs"
RETRIES = "retries"
DB = "db"
SERVICE_TYPE = "service-type"
SERVICE_TYPE_ESSENTIAL = "essential"
SERVICE_TYPE_FILE= "file"
SERVICE_TYPE_METADATA= "metadata"
SERVICE_TYPE_EXPORT = "export"
SERVICE_TYPE_PV_PULLER = "pv_puller"
SERVICE_TYPES = [SERVICE_TYPE_ESSENTIAL, SERVICE_TYPE_FILE, SERVICE_TYPE_METADATA, SERVICE_TYPE_EXPORT, SERVICE_TYPE_PV_PULLER]

MODEL_FILE_DIR = "models-loc"
LOADER_QUEUE = "LOADER_QUEUE"
FILE_QUEUE = "FILE_QUEUE"
METADATA_QUEUE = "METADATA_QUEUE"
EXPORTER_QUEUE = "EXPORTER_QUEUE"
#file validation 
FILE_INVALID_REASON = "invalid_reason"

#upload
UPLOAD_STATUS ="upload_status"
RELEASE = "release"
ARCHIVE_RELEASE = "archive_release"
#Batch
BATCH_BUCKET = "bucketName"
FILE_PREFIX = "filePrefix"
BATCH_COLLECTION = "batch"
BATCH_ID = "batchID"
SUCCEEDED = "succeeded"
ERRORS = "errors"
WARNINGS = "warnings"
CREATED_AT = "createdAt"
UPDATED_AT = "updatedAt"
STATUS= "status"
BATCH_STATUS_FAILED = "Failed"
BATCH_TYPE_METADATA ="metadata"
BATCH_STATUS_UPLOADED = "Uploaded"
SUBMISSION_COLLECTION="submissions"
DATA_COMMON_NAME ="dataCommons"
ORCID = "ORCID"
BATCH_INTENTION = "metadataIntention"
SUBMISSION_INTENTION_NEW = "New"
SUBMISSION_INTENTION_DELETE = "Delete"
SUBMISSION_INTENTION_NEW_UPDATE = "New/Update"
BATCH_INTENTION_UPDATE = "Add/Change"

# export
EXPORT_METADATA = "metadata"
EXPORT_ROOT_PATH = "rootPath"
DELETE_VALUE = "<delete>"

# file
FILE_ID = "dataRecordID"
S3_FILE_INFO = "s3FileInfo"
ID = "_id"
SIZE ="size"
MD5 = "md5"
DATA_COLlECTION = "dataRecords"
FILE_NAME = "fileName"
STATUS_ERROR = "Error"
STATUS_WARNING = "Warning"
STATUS_PASSED = "Passed"
STATUS_NEW = "New"
SUBMISSION_ID = "submissionID"
NODE_ID = "nodeID"
NODE_TYPE = "nodeType"
S3_BUCKET_DIR = "s3_bucket_drive"
FILE_ERRORS = "fileErrors"
PROPERTIES = "props"
PARENTS = "parents"
PARENT_TYPE = "parentType"
PARENT_ID_VAL = "parentIDValue"
PARENT_ID_NAME = "parentIDPropName"
RAW_DATA = "rawData"

FILE_NAME_FIELD = "name-field"
FILE_SIZE_FIELD = "size-field"
FILE_MD5_FIELD = "md5-field"
FILE_MD5_COLLECTION = "fileMD5"
LAST_MODIFIED = "LastModified"

#data model
DATA_COMMON = "data_commons"
VERSION = "version"
MODEL_SOURCE = "source_files"
NAME_PROP = "name"
DESC_PROP = "description"
ID_PROPERTY = "id_property"
MODEL = "model"
VALUE_PROP = "value"
VALUE_EXCLUSIVE = "exclusive"
ALLOWED_VALUES = "permissible_values"
RELATION_LABEL = "label"
RELATION_PARENT_NODE ="parent_nodes"
NODE_LABEL = "node"
NODES_LABEL = "nodes"
IDS = "id_fields"
ID_FIELD = "id-field"
RELATIONSHIPS = "relationships"
NODE_PROPERTIES = "properties"
PROP_REQUIRED="required"
TYPE ="type"
MODELS_DEFINITION_FILE = "content.json"
TIER = "TIER"
TIER_CONFIG = "tier"
FILE_SIZE = "file_size"
MIN = 'minimum'
MAX = 'maximum'
VALIDATION_RESULT = "result"
VALIDATED_AT = "validatedAt"
FILE_VALIDATION_STATUS = "fileValidationStatus"
METADATA_VALIDATION_STATUS = "metadataValidationStatus"
CROSS_SUBMISSION_VALIDATION_STATUS = "crossSubmissionStatus"
MODEL_VERSION = "modelVersion"
KEY = "key"
LIST_DELIMITER_PROP = "list-delimiter"
DEF_MAIN_NODES = "main-nodes"
#s3 download directory
S3_DOWNLOAD_DIR = "s3_download"
ROOT_PATH = "rootPath"
# sqs message
SCOPE = "scope"
SQS_TYPE = "type"
TYPE_LOAD = "Load Metadata"
TYPE_DELETE = "Delete Metadata"
TYPE_METADATA_VALIDATE = "Validate Metadata"
TYPE_FILE_VALIDATE = "Validate Single File"
TYPE_FILE_VALIDATE_ALL = "Validate Submission Files"
TYPE_EXPORT_METADATA = "Export Metadata"
TYPE_COMPLETE_SUB = "Complete Submission"
TYPE_CROSS_SUBMISSION = "Validate Cross-submission"
RESTORE_DELETED_DATA_FILES = "Restore Deleted Data Files"
FAILED = "Failed"
ADDITION_ERRORS = "additionalErrors"
STUDY_ABBREVIATION = "studyAbbreviation"
LIST_DELIMITER_PROP = "list-delimiter"

#dataRecords
CRDC_ID = "CRDC_ID"
RELEASE_COLLECTION = "release"
ORIN_FILE_NAME = "orginalFileName"

#submission level validation
SUBMISSION_INTENTION ="intention"
SUBMISSION_STATUS = "status"
SUBMISSION_STATUS_SUBMITTED = "Submitted"

#Submission release status
SUBMISSION_REL_STATUS = "status"
SUBMISSION_REL_STATUS_RELEASED = "Released"
SUBMISSION_REL_STATUS_DELETED= "Deleted"

# validation collection
VALIDATION_COLLECTION = "validation"
VALIDATION_ID = "validationID"
VALIDATION_ENDED= "validationEnded"

#DCF Manifest
PROD_BUCKET_CONFIG_NAME = "production_bucket_name"
DCF_PREFIX = "dg.4DFC/"
STUDY_ID = "studyID"
DBGA_PID = "dbGaPID"
CONTROL_ACCESS = "controlledAccess"
DM_BUCKET_CONFIG_NAME = "dm_bucket"
DATASYNC_ROLE_ARN_ENV = "DATASYNC_ROLE_ARN"
DATASYNC_LOG_ARN_ENV = "DATASYNC_LOG_ARN"
DATASYNC_ROLE_ARN_CONFIG = "datasync_role"
DATASYNC_LOG_ARN_CONFIG = "datasync_log_arn"

CONFIG_COLLECTION = "configuration"
CONFIG_TYPE = "type"
CONFIG_KEY = "keys"
CDE_COLLECTION = "CDE"
CDE_CODE = "CDECode"
CDE_VERSION = "CDEVersion"
CDE_FULL_NAME = "CDEFullName"
CDE_API_URL = "cde-data-element-api"
CDE_TERM = "Term"
CDE_PERMISSIVE_VALUES = "PermissibleValues"

SYNONYM_API_URL = "synonym-api-url"

TERM_CODE = "Code"
TERM_VERSION = "Version"

ENTITY_TYPE = "entityType"

SUBMISSION_HISTORY = "history"
RELEASE_AT = "releasedAt"

QC_RESULT_ID = "qcResultID"
QC_COLLECTION = "qcResults"
QC_SEVERITY = "severity"
VALIDATION_TYPE_METADATA = "metadata"
VALIDATION_TYPE_FILE= "data file"
BATCH_IDS = "batchIDs"
QC_VALIDATE_DATE = "validatedDate"
QC_ORIGIN = "origin"
QC_ORIGIN_METADATA_VALIDATE_SERVICE = "Metadata Validation Service"
QC_ORIGIN_FILE_VALIDATE_SERVICE = "Data File Validation Service"
DISPLAY_ID = "displayID"
LATEST_BATCH_DISPLAY_ID ="latestBatchDisplayID"
UPLOADED_DATE = "uploadedDate"
LATEST_BATCH_ID = "latestBatchID"
SUBMITTED_ID = "submittedID"
QC_VALIDATION_TYPE = "validationType"
DATA_RECORD_ID = "dataRecordID"
SUBMISSION_DATA_TYPE = "dataType"
SUBMISSION_DATA_TYPE_METADATA_ONLY = "Metadata Only"
MESSAGE_TITLE = "title"
SYNONYM_COLLECTION = "synonyms"
PV_TERM = "equivalent_term"
SYNONYM_TERM = "synonym_term"

STUDY_COLLECTION = "approvedStudies"
ORGANIZATION_COLLECTION = "organization"
PROPERTY_NAMES = "property-names"
OMIT_DCF_PREFIX = "omit-DCF-prefix"
DATA_FILE_LOCATION = "dataFileLocation"
S3_PREFIX = "rootPath"
PROPERTY_PATTERN = "pattern"

USER_COLLECTION = "users"

DELETE_COMMAND = "<delete>"

COMPOSITION_KEY = "composition_key"

PV_CONCEPT_CODE_COLLECTION = "pvConceptCodes"
CONCEPT_CODE = "conceptCode"
PERMISSIBLE_VALUE = "pv"
GENERATED_PROPS = "generatedProps"

